### ISSUE TITLE
streaming is not working

### ISSUE THREAD

**Issue by axeff** [dmotz/soundscrape#1]
just installed soundscrape and tried "soundscrape claque very-special -p" as in description.
does not stream, but fetch the track.

update: installed via npm

**Comment by dmotz** [comment]
Do you have version 0.2.0 installed? Try `npm uninstall -g soundscrape` then `npm install -g soundscrape` and try it again.

Do you have SoX installed? I'm guessing you'd get an error if you didn't.

**Comment by axeff** [comment]
just uninstalled and installed again. npm -v soundscrape gives me 1.1.4. might be the problem.
shouldn't npm install the latest version? i'll try to install with version number.

**Comment by dmotz** [comment]
`npm -v` just gives you the version of npm itself. `npm info soundscrape` should tell you the latest version of soundscrape (0.2.0). `npm ls -g | grep soundscrape` should show 0.2.0 after you install.

**Comment by axeff** [comment]
just realized that too. version is 0.1.6.
if I try to install soundscrape@0.2.0 i get errors:
npm ERR! Not compatible with your version of node/npm: soundscrape@0.2.0
npm ERR! Required: {"node":"0.10.x"}
npm ERR! Actual:   {"npm":"1.1.4","node":"0.6.19"}

so i will update node, try again and let you know.

**Comment by axeff** [comment]
so I updated node and now i have version 0.2.0 of soundscrape.
now when i run your example "soundscrape claque very-special -p" i get the following error:

Error: In /usr/local/bin/soundscrape, Parse error on line 43: Unexpected 'INDENT'
    at Object.parseError (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/parser.js:483:11)
    at Object.parse (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/parser.js:535:22)
    at exports.compile.compile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:54:27)
    at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:124:34)
    at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:166:29)
    at /usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:141:18
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)

**Comment by dmotz** [comment]
Try `npm update -g coffee-script`. It looks like I need to fix how that dependency is bundled.

**Comment by axeff** [comment]
updated like suggested - now one step further.
next error though:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: This socket is closed.
  at Socket._write (net.js:635:19)
  at doWrite (_stream_writable.js:221:10)
  at writeOrBuffer (_stream_writable.js:211:5)
  at Socket.Writable.write (_stream_writable.js:180:11)
  at Socket.write (net.js:613:40)
  at apply (/usr/local/lib/node_modules/soundscrape/node_modules/ear-pipe/index.js:14:26)
  at [object Object].EarPipe._write (/usr/local/lib/node_modules/soundscrape/node_modules/ear-pipe/index.js:44:10)
  at doWrite (_stream_writable.js:221:10)
  at writeOrBuffer (_stream_writable.js:211:5)
  at [object Object].Writable.write (_stream_writable.js:180:11)
  at write (_stream_readable.js:583:24)
  at flow (_stream_readable.js:592:7)
  at _stream_readable.js:560:7
  at process._tickCallback (node.js:415:13)

update: the first time after reboot I ran this I got: Error: This socket has been ended by the other party. And after that I always get the error from above.

**Comment by dmotz** [comment]
Do you have [SoX](http://sox.sourceforge.net)? It's needed only for the audio playing functionality.

**Comment by axeff** [comment]
Yes, SoX v14.4.0

**Comment by dmotz** [comment]
Hmm can you run `npm update -g soundscrape` again to get 0.2.1 and then tell me what you get?

**Comment by axeff** [comment]
updated successfully, but nothing changed. same error first: This socket has been ended by the other party
and then always: This socket is closed.

BTW, system is a raspberry pi with wheezy running, if that information helps...

**Comment by dmotz** [comment]
Does it work if you omit the `-p` arg?

**Comment by axeff** [comment]
Yes, that works. I'll try some debugging also.

**Comment by axeff** [comment]
Tried on my Mac and works like a charm. I get the feeling it is related to the sox installation... I think I'll reinstall it

**Comment by axeff** [comment]
I don't have any ideas left. I'm stuck.

**Comment by dmotz** [comment]
Try this to test SoX directly:

`curl http://ia700500.us.archive.org/12/items/ird059/tcp_d1_06_the_lincolnshire_poacher_mi5_irdial.mp3 | play -b 16 -t mp3 -`

**Comment by axeff** [comment]
sox FAIL sox: Not enough input filenames specified
that might be it. just loading the file via curl works though.

**Comment by dmotz** [comment]
Yeah I don't know why the API would be different between Debian and OSX. The `-` at the end of the SoX arguments specifies to read from stdin.

**Comment by axeff** [comment]
tried it with wav and it works. so it might be caused by mp3 codec. do you know which lib sox uses?

**Comment by dmotz** [comment]
Ah that makes sense. I think you have to install the `lame` package for Debian, see: https://wiki.debian.org/MultimediaCodecs

**Comment by axeff** [comment]
there we go! that was it!
soundscrape is streaming.

if anyone is running into this, the problem is the <b>mp3 lib sox uses on wheezy</b> (raspberry pi).
install that one and it is working: http://packages.debian.org/wheezy/libsox-fmt-mp3

thx dmotz for escorting me here.

**Comment by dmotz** [comment]
Awesome, glad you've got it working!
