### ISSUE TITLE
Problem downloading.

### ISSUE THREAD

**Issue by luckcolors** [dmotz/soundscrape#3]
Hello.
I've used your tool for downloading but it sems rejetting every artist name i put (it also reject yours) leaving me with this error: artist not found.
Can you help me? thanks in advance :).

**Comment by dmotz** [comment]
Yeah, Soundcloud just recently changed a lot of things which broke this tool. If I get a chance, I'll look into fixing it, otherwise open to pull requests.

**Comment by bahamas10** [comment]
:+1: broken for me too

**Comment by ChristopherNeuwirth** [comment]
+1

**Comment by luckcolors** [comment]
Closing this as i would like to not have it on my open issues page anymore.
As apparently this will never get fixed. Last update on the repo was 3 years ago.
